import { gsap, Power3 } from "gsap";
import type { NextPage } from "next";
import Head from "next/head";
import React from "react";
import CustomCursor from "../components/CustomCursor";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const techs: string[] = [
    "HTML",
    "CSS",
    "Javascript",
    "Typescript",
    "React",
    "Angular",
    "Next.js",
    "Nuxt",
    "Mui",
    "Express",
    "Nest.js",
    "Mongodb",
    "PostgreSQL",
    "Git / GitHub",
    "Sass / Scss",
  ];
  const [darkTheme, setDarkTheme] = React.useState<any>(undefined);
  const aboutRef = React.useRef(null);
  const techRef = React.useRef(null);
  const contactRef = React.useRef(null);

  const handleToggle = () => {
    setDarkTheme(Boolean(!darkTheme));
  };

  React.useEffect(() => {
    if (darkTheme !== undefined) {
      if (darkTheme) {
        document.documentElement.setAttribute("data-theme", "dark");
        window.localStorage.setItem("theme", "dark");
      } else {
        document.documentElement.removeAttribute("data-theme");
        window.localStorage.setItem("theme", "light");
      }
    }
  }, [darkTheme]);

  React.useEffect(() => {
    const root = window.document.documentElement;
    const initialColorValue = root.style.getPropertyValue(
      "--initial-color-mode"
    );
    setDarkTheme(initialColorValue === "dark");
  }, []);

  React.useEffect(() => {
    gsap.from([aboutRef.current, techRef.current, contactRef.current], {
      opacity: 0,
      duration: 1,
      y: -20,
      stagger: {
        amount: 1,
      },
    });
    gsap.to([aboutRef.current, techRef.current, contactRef.current], {
      opacity: 1,
      duration: 1,
      y: 0,
      stagger: {
        amount: 1,
      },
    });
  }, []);

  return (
    <div>
      <CustomCursor />
      <Head>
        <title>Aziz Ouichni</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <nav className={styles.navigation}>
          <div>by aziz ouichni</div>
          <div onClick={handleToggle} className={styles.dark}>
            {!darkTheme ? "so dark?" : "lot of light?"}
          </div>
          <div>2022</div>
        </nav>
      </header>

      <main className={styles.main}>
        <div ref={aboutRef} className={styles.container}>
          <p className={styles.intro}>
            Hi! My name is Mohamed Aziz Ouichni and I&apos;m a fullstack
            developer, currently working (happily) at{" "}
            <span className={styles.bulldozer}>bulldozer</span>.🦊
          </p>
        </div>

        <div className={styles.container} ref={techRef}>
          <p className={styles.intro}>
            Technology I&apos;ve worked & <span>dabbled</span> with:
          </p>
          <ul className={styles.list}>
            {techs.map((tech, i) => (
              <li key={i} className={styles.tech}>
                {tech}
              </li>
            ))}
          </ul>
        </div>

        <div className={styles.container} ref={contactRef}>
          <p className={styles.introcontact}>
            If youadadada questions or would like to have a chat, don&apos;t
            hesitate to get in {" "}
            <a
              href="https://www.linkedin.com/in/ouichniaziz/"
              target="_blank"
              rel="noreferrer"
            >
              <span className={styles.contact}>touch.</span>
            </a>
          </p>
        </div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
};

export default Home;
